### ISSUE TITLE
TypeError: Cannot read property 'endsWith' of undefined

### ISSUE THREAD

**Issue by maple-leaf** [yibn2008/find-process#40]
```
                return row.Name === cond.name || (row.Name.endsWith('.exe') && row.Name.slice(0, -4) === cond.name)
```

This line sometimes can raise a error like below
```
TypeError: Cannot read property 'endsWith' of undefined
    at C:\Users\balbalba\balbalba\resources\app.asar\node_modules\find-process\lib\find_process.js:140:60
    at Array.filter (<anonymous>)
    at ChildProcess.<anonymous> (C:\Users\mobra\balbalba\balbalba\resources\app.asar\node_modules\find-process\lib\find_process.js:135:12)
    at ChildProcess.emit (events.js:203:13)
    at ChildProcess.EventEmitter.emit (domain.js:476:20)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
```

**Comment by PandaTsui** [comment]
me too
