### ISSUE TITLE
v1.4.5: Error: port must be a number

### ISSUE THREAD

**Issue by rjurado01** [yibn2008/find-process#53]
### 1.4.4

Works Ok

```
$ yarn find-process -p 3000
yarn run v1.22.10
$ /home/.../node_modules/.bin/find-process -p 3000
(Not all processes could be identified, non-owned process info
 will not be shown, you would have to be root to see it all.)
Found 1 process

[localhost:3000)]
pid: 17002
cmd: puma 5.5.2 (tcp://localhost:3000) [meka-erp]

Done in 0.13s.
```

### 1.4.5

Error

```
$ yarn find-process -p 3000
yarn run v1.22.10
$ /home/.../node_modules/.bin/find-process -p 3000
Error: port must be a number
    at /home/.../node_modules/find-process/lib/find.js:60:162
    at new Promise (<anonymous>)
    at find (/home/.../node_modules/find-process/lib/find.js:56:10)
    at Object.<anonymous> (/home/.../node_modules/find-process/bin/find-process.js:59:1)
    at Module._compile (internal/modules/cjs/loader.js:1015:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1035:10)
    at Module.load (internal/modules/cjs/loader.js:879:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47
error Command failed with exit code 1.
```

### Details
* OS: Linux ... 5.11.0-40-generic 44~20.04.2-Ubuntu SMP Tue Oct 26 18:07:44 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
* node: v12.19.0

**Comment by yibn2008** [comment]
@rjurado01 already fixed and released the v1.4.6, please checkout.
